DROP TABLE devices IF EXISTS;


CREATE TABLE devices (
                         id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name        VARCHAR(100) NOT NULL,
                         brand       VARCHAR(100) NOT NULL,
                         state       VARCHAR(50) NOT NULL,
                         creation_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
